baseURL = 'https://soother.systems/'
title = 'SOOTHER'
theme = 'cactus'
languageCode = "en-us"
copyright = "CICADIDAE SYSTEMS" # cactus will use title if copyright is not set
# googleAnalytics = "UA-1234-5"
hugoEnvironment = "production"

# summaryLength = 2

# Main menu which appears below site header.

[[menu.main]]
name = "Concept"
url = "/concept"
weight = 1

[[menu.main]]
name = "Docs"
url = "/docs"
weight = 2

[[menu.main]]
name = "Prototype"
url = "/prototype"
weight = 3

[[menu.main]]
name = "Voice"
url = "/voice"
weight = 4

[[menu.main]]
name = "Next-Gen"
url = "/next-gen"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  css = ["css/custom.css"]
  mainSectionTitle = "Docs"
  mainSection = "docs"
  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default

  # Home page settings
  description = "SOOTHER is the prototype of an AI ASMR voice companion created in 2021 by [Claire Tolan](https://cst.yt/)."

  moardescription = "This website hosts comprehensive documentation of SOOTHER. [Concept](/concept) explains the fundamentals of SOOTHER's personality and ASMR. Technical documentation of SOOTHER is collected in [docs](/docs). Screen grabs and videos of [SOOTHER's prototype](/prototype) show the project's state at the end of the S+T+ARTS residency in June 2021, and [voice](/voice) contains information about SOOTHER's speech dataset and samples from training and inference. Finally, [Next-Gen](/next-gen) speculates about the possible futures of the project, and [About](/about) details practical information and credits."
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

 